name = "wedding"
type = "webpack"
account_id = "323b0253f67c95c7bf534629f3d2fc04"
workers_dev = false

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
zone_id = "d65a2dc69a0f67ea7514971fb2e877d7"
route = "turnonthefawcetts.com/*"

[env.staging]
zone_id = "d65a2dc69a0f67ea7514971fb2e877d7"
route = "staging.turnonthefawcetts.com/*"